# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/jjthrash/Downloads/OpenCV-2.2.0/3rdparty/zlib/CMakeLists.txt
	/usr/local/Cellar/cmake/2.8.3/bin/cmake -H/Users/jjthrash/Downloads/OpenCV-2.2.0 -B/Users/jjthrash/Downloads/OpenCV-2.2.0
